[package]
name = "sniffer-agent"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "magnet-sniffer-agent"
path = "src/main.rs"


[dependencies]
sniffer-common = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }


[lints]
workspace = true
