[workspace]
members = ["sniffer-backend", "sniffer-agent", "sniffer-common"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = { version = "0.11.19" }
anyhow = { version = "1.0.102" }
thiserror = { version = "2.0.18" }
bt_bencode = { version = "0.8.2" }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "fmt",
    "std",
    "time",
] }
tracing-appender = { version = "0.2.5" }
dotenvy = "0.15.7"
hex = "0.4.3"
rand = { version = "0.10.1" }
sniffer-common = { path = "./sniffer-common" }
time = { version = "0.3.49", default-features = false, features = ["macros"] }
getrandom = { version = "0.4.3" }
serde_bencode = { version = "0.2.4" }
crc = "3.4.0"
reqwest = { version = "0.13.4", default-features = false }
url = "2.5.8"
futures = "0.3.32"
sha1 = "0.11.0"
async-trait = "0.1"

[profile.release]
lto = true
